#pragma once

#define NTLKAP_NAME_A         "KRAFTWAY_APMDZ_SSP_AP_V_1_0"
#define NTLKAP_NAME           TEXT("KRAFTWAY_APMDZ_SSP_AP_V_1_0")


#define NTLKAP_COMMENT        NTLKAP_NAME
#define NTLKAP_COMMENT_A      NTLKAP_NAME_A

#define NTLKAP_MAX_TOKEN_SIZE  0x4400

#define NTLK_CRED_NULLSESSION  SECPKG_CRED_RESERVED

#define SYSWOW64_PATH		   "%SystemRoot%\\SysWOW64\\"
